// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PortfolioWebsite.Api.Data;

#nullable disable

namespace PortfolioWebsite.Api.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20261009161434_AddResumeAnalysis")]
    partial class AddResumeAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.AdminToken", b =>
                {
                    b.Property<Guid>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("AdminTokenId");

                    b.ToTable("AdminTokens");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.AdversarialCaseResult", b =>
                {
                    b.Property<Guid>("AdversarialCaseResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdversarialRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BlockedByContentFilter")
                        .HasColumnType("boolean");

                    b.Property<string>("CaseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("PlantedClaim")
                        .HasColumnType("text");

                    b.Property<string>("PremiseHandling")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolCalls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdversarialCaseResultId");

                    b.HasIndex("AdversarialRunId");

                    b.HasIndex("CaseKey");

                    b.ToTable("AdversarialCaseResults");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.AdversarialRun", b =>
                {
                    b.Property<Guid>("AdversarialRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CasesAnswered")
                        .HasColumnType("integer");

                    b.Property<int>("CasesJudged")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JudgeModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PassRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Passed")
                        .HasColumnType("integer");

                    b.Property<int>("Scored")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("running");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TargetModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCases")
                        .HasColumnType("integer");

                    b.HasKey("AdversarialRunId");

                    b.HasIndex("StartedAt");

                    b.ToTable("AdversarialRuns");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Error")
                        .HasColumnType("boolean");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ResponseTookMs")
                        .HasColumnType("real");

                    b.Property<Guid?>("SessionTrackingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TokenLimitReached")
                        .HasColumnType("boolean");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.EmbeddingProjection", b =>
                {
                    b.Property<Guid>("EmbeddingProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SubLabel")
                        .HasColumnType("text");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("EmbeddingProjectionId");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("EmbeddingProjections");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Information", b =>
                {
                    b.Property<Guid>("InformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("InformationId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.JobFitRequirement", b =>
                {
                    b.Property<Guid>("JobFitRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobFitRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequirementKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobFitRequirementId");

                    b.HasIndex("JobFitRunId");

                    b.HasIndex("Status", "Importance");

                    b.ToTable("JobFitRequirements");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.JobFitRun", b =>
                {
                    b.Property<Guid>("JobFitRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<double?>("FitScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsJobDescription")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("MustHavesMet")
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ResponseTookMs")
                        .HasColumnType("real");

                    b.Property<Guid?>("SessionTrackingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("JobFitRunId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("JobFitRuns");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Keyword", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KeywordId");

                    b.HasIndex("InformationId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EndYear")
                        .HasColumnType("text");

                    b.Property<string>("ImpactStatement")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartYear")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterEmail", b =>
                {
                    b.Property<Guid>("RecruiterEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .HasColumnType("text");

                    b.Property<string>("GmailDraftId")
                        .HasColumnType("text");

                    b.Property<string>("GmailMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GmailThreadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Personalized")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecruiterEmailId");

                    b.HasIndex("GmailMessageId")
                        .IsUnique();

                    b.HasIndex("GmailThreadId");

                    b.ToTable("RecruiterEmails");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterPitch", b =>
                {
                    b.Property<Guid>("RecruiterPitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AnnualPay")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RecruiterEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecruiterName")
                        .HasColumnType("text");

                    b.Property<Guid>("RecruiterPostingId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecruitingAgency")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.HasKey("RecruiterPitchId");

                    b.HasIndex("RecruiterEmailId");

                    b.HasIndex("RecruiterPostingId");

                    b.ToTable("RecruiterPitches");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterPosting", b =>
                {
                    b.Property<Guid>("RecruiterPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AnnualPay")
                        .HasColumnType("double precision");

                    b.Property<bool>("CanReply")
                        .HasColumnType("boolean");

                    b.Property<string>("Conflicts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("ContractTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HiringCompany")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Missing")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("WorkArrangement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecruiterPostingId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("ReviewStatus", "LastSeenAt");

                    b.ToTable("RecruiterPostings");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterTriageSettings", b =>
                {
                    b.Property<int>("RecruiterTriageSettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("AcceptableLocations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AllowHybrid")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOnsite")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowRemote")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedEmploymentTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DealbreakerContractTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreeTextRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OK");

                    b.Property<double>("HoursPerYear")
                        .HasColumnType("double precision");

                    b.Property<double>("HybridPayFloor")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OnsitePayFloor")
                        .HasColumnType("double precision");

                    b.Property<double>("RemotePayFloor")
                        .HasColumnType("double precision");

                    b.Property<bool>("ShadowMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("TriageEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RecruiterTriageSettingsId");

                    b.ToTable("RecruiterTriageSettings");

                    b.HasData(
                        new
                        {
                            RecruiterTriageSettingsId = 1,
                            AcceptableLocations = "[\"Oklahoma City\",\"OKC\",\"Edmond\",\"Moore\",\"Midwest City\",\"Del City\",\"Yukon\",\"Mustang\",\"Bethany\",\"Warr Acres\",\"Nichols Hills\",\"The Village\",\"Choctaw\",\"Norman\",\"Tinker AFB\",\"Tinker Air Force Base\",\"Piedmont\",\"Newcastle\",\"Spencer\",\"Harrah\",\"Jones\"]",
                            AllowHybrid = true,
                            AllowOnsite = true,
                            AllowRemote = true,
                            AllowedEmploymentTypes = "[\"full_time\",\"contract_to_hire\"]",
                            DealbreakerContractTerms = "[\"c2c\",\"1099\"]",
                            FreeTextRequirements = "The role must be primarily hands-on software development or AI engineering, where I'm writing code. Not desktop support, help desk, manual QA, project management, security analysis, or BI reporting without real development.",
                            HomeState = "OK",
                            HoursPerYear = 2080.0,
                            HybridPayFloor = 90000.0,
                            OnsitePayFloor = 90000.0,
                            RemotePayFloor = 90000.0,
                            ShadowMode = true,
                            TriageEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeAnalysis", b =>
                {
                    b.Property<Guid>("ResumeAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("running");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("ResumeAnalysisId");

                    b.HasIndex("ResumeFileId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ResumeAnalyses");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeFile", b =>
                {
                    b.Property<Guid>("ResumeFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ResumeFileId");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\"");

                    b.HasIndex("Sha256");

                    b.ToTable("ResumeFiles");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeSuggestion", b =>
                {
                    b.Property<Guid>("ResumeSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.HasKey("ResumeSuggestionId");

                    b.HasIndex("ResumeAnalysisId");

                    b.HasIndex("Status", "ResumeAnalysisId");

                    b.ToTable("ResumeSuggestions");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.WorkExperience", b =>
                {
                    b.Property<Guid>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndYear")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("StartYear")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkExperienceId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("ProjectWorkExperience", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkExperienceId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "WorkExperienceId");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("ProjectWorkExperience");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.AdversarialCaseResult", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.AdversarialRun", null)
                        .WithMany("Cases")
                        .HasForeignKey("AdversarialRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.JobFitRequirement", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.JobFitRun", null)
                        .WithMany("Requirements")
                        .HasForeignKey("JobFitRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Keyword", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.Information", "Information")
                        .WithMany("Keywords")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Information");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterPitch", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.RecruiterEmail", "Email")
                        .WithMany("Pitches")
                        .HasForeignKey("RecruiterEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioWebsite.Api.Data.Models.RecruiterPosting", "Posting")
                        .WithMany("Pitches")
                        .HasForeignKey("RecruiterPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeAnalysis", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.ResumeFile", "ResumeFile")
                        .WithMany()
                        .HasForeignKey("ResumeFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeFile");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeSuggestion", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.ResumeAnalysis", "Analysis")
                        .WithMany("Suggestions")
                        .HasForeignKey("ResumeAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ProjectWorkExperience", b =>
                {
                    b.HasOne("PortfolioWebsite.Api.Data.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioWebsite.Api.Data.Models.WorkExperience", null)
                        .WithMany()
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.AdversarialRun", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.Information", b =>
                {
                    b.Navigation("Keywords");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.JobFitRun", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterEmail", b =>
                {
                    b.Navigation("Pitches");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.RecruiterPosting", b =>
                {
                    b.Navigation("Pitches");
                });

            modelBuilder.Entity("PortfolioWebsite.Api.Data.Models.ResumeAnalysis", b =>
                {
                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
