/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/AdminChatLog': RouteRecordInfo<'/admin/AdminChatLog', '/admin/AdminChatLog', Record<never, never>, Record<never, never>>,
    '/admin/AdminInformation': RouteRecordInfo<'/admin/AdminInformation', '/admin/AdminInformation', Record<never, never>, Record<never, never>>,
    '/admin/AdminProjects': RouteRecordInfo<'/admin/AdminProjects', '/admin/AdminProjects', Record<never, never>, Record<never, never>>,
    '/admin/AdminWorkExperience': RouteRecordInfo<'/admin/AdminWorkExperience', '/admin/AdminWorkExperience', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/verify': RouteRecordInfo<'/admin/verify', '/admin/verify', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/Projects': RouteRecordInfo<'/Projects', '/Projects', Record<never, never>, Record<never, never>>,
    '/resume': RouteRecordInfo<'/resume', '/resume', Record<never, never>, Record<never, never>>,
    '/testimonial': RouteRecordInfo<'/testimonial', '/testimonial', Record<never, never>, Record<never, never>>,
    '/work-experience': RouteRecordInfo<'/work-experience', '/work-experience', Record<never, never>, Record<never, never>>,
  }
}
