export const dark = {
  dark: true,
  colors: {
    background: '#FFFFFF',
    surface: '#F8F8F2',
    'surface-bright': '#F8F8F2',
    'surface-light': '#F8F8F2',
    'surface-variant': '#F8F8F2',
    'on-surface-variant': '#F8F8F2',
    primary: '#6272A4',
    'primary-darken-1': '#44475A',
    secondary: '#8BE9FD',
    'secondary-darken-1': '#8BE9FD',
    error: '#FF5555',
    info: '#F1FA8C',
    success: '#50FA7B',
    warning: '#FFB86C',
  },
  variables: {
    'border-color': '#F8F8F2',
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.6,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.04,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#212529',
    'theme-on-kbd': '#FFFFFF',
    'theme-code': '#F5F5F5',
    'theme-on-code': '#000000',
  },
}
