<template>
  <div class="resume-page">

    <!-- Sticky toolbar -->
    <div class="resume-toolbar">
      <div class="resume-toolbar__main">

        <v-btn icon variant="text" size="small" @click="toggleExpand"
          :aria-label="isExpanded ? 'Collapse info' : 'Expand info'" class="toolbar-icon-btn">
          <v-icon>{{ isExpanded ? 'mdi-information' : 'mdi-information-outline' }}</v-icon>
        </v-btn>

        <a :href="pdfLink" target="_blank" rel="noopener noreferrer" class="toolbar-pdf-link">
          <v-icon size="18" class="mr-1">mdi-file-pdf-box</v-icon>
          Official Resume
        </a>

        <v-divider vertical class="toolbar-divider mx-3 d-none d-sm-flex" />

        <div class="toolbar-regen">
          <div class="tailor-section">
            <v-text-field v-model="tailorTitle" label="Tailor for a role..." variant="outlined" density="comfortable"
              hide-details clearable style="min-width: 220px" />
            <v-btn v-if="tailorTitle" variant="text" size="small" :color="showJd ? 'secondary' : 'default'"
              @click="showJd = !showJd">
              {{ showJd ? 'Hide' : '+ Add' }} Job Description
            </v-btn>
          </div>

          <v-expand-transition>
            <v-textarea v-if="showJd && tailorTitle" v-model="jobDescription"
              label="Paste the job description (optional)" variant="outlined" density="comfortable" rows="6" auto-grow
              class="mt-2" hint="The more detail you paste, the more targeted the resume will be" persistent-hint />
          </v-expand-transition> <v-btn color="secondary" variant="tonal" size="small" :loading="resumeStore.loading"
            @click="triggerFetch" class="regen-btn">
            <v-icon size="16" class="mr-1">mdi-refresh</v-icon>
            <span class="d-none d-sm-inline">Regenerate</span>
          </v-btn>
        </div>

      </div>

      <v-expand-transition>
        <div v-if="isExpanded" class="resume-toolbar__info">
          <v-divider class="mb-3" />
          <p class="info-text">
            This resume is <strong>generated by AI</strong> using information about Samuel's actual
            experience — so it's always up to date. You can tailor it to a specific role using the
            field above.
          </p>
          <p class="info-text">
            Prefer a traditional format?
            <a :href="pdfLink" target="_blank" rel="noopener noreferrer" class="info-link">
              Download the official PDF resume here.
            </a>
          </p>
        </div>
      </v-expand-transition>
    </div>

    <!-- Resume content -->
    <div class="resume-content">
      <div v-if="resumeStore.loading" class="resume-loading">
        <v-progress-circular indeterminate color="secondary" size="56" />
        <p class="resume-loading__text">Generating my resume...</p>
      </div>
      <div v-else v-html="resumeStore.resumeContent" class="resume-html" />
    </div>

  </div>
</template>

<script setup>
import { ref, onBeforeUnmount } from 'vue'
import { useResumeStore } from '@/stores/resumeStore'

const resumeStore = useResumeStore()
const isExpanded = ref(false)
const tailorTitle   = ref('')
const jobDescription = ref('')
const showJd        = ref(false)
const pdfLink = ref(import.meta.env.VITE_RESUME_PDF_LINK)

// Debounce: only auto-fetch 800ms after the user stops typing
let debounceTimer = null

// Immediate fetch on Enter or button click
function triggerFetch() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    console.log(tailorTitle);
    console.log(jobDescription);
    resumeStore.fetchResume(
      tailorTitle.value || undefined,
      jobDescription.value || undefined
    )
  }, 600)
}

function toggleExpand() {
  isExpanded.value = !isExpanded.value
}

onBeforeUnmount(() => {
  clearTimeout(debounceTimer)
})
</script>

<style scoped>
.resume-page {
  display: flex;
  flex-direction: column;
  height: 100%;
  font-family: 'Raleway', sans-serif;
}

/* ── Toolbar ── */
.resume-toolbar {
  position: sticky;
  top: 0;
  z-index: 10;
  background: rgb(var(--v-theme-surface));
  border-bottom: 1px solid rgba(var(--v-theme-secondary), 0.15);
  padding: 0.6rem 1.25rem;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.25);
}

.resume-toolbar__main {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex-wrap: wrap;
  min-height: 44px;
}

.toolbar-icon-btn {
  color: rgba(var(--v-theme-on-surface), 0.6) !important;
  flex-shrink: 0;
  /* Polished focus ring */
  border-radius: 6px;
}

.toolbar-icon-btn:focus-visible {
  outline: 2px solid rgb(var(--v-theme-secondary));
  outline-offset: 2px;
}

.toolbar-pdf-link {
  display: inline-flex;
  align-items: center;
  font-size: 0.85rem;
  font-weight: 600;
  color: rgb(var(--v-theme-secondary)) !important;
  text-decoration: none;
  white-space: nowrap;
  flex-shrink: 0;
  border-radius: 4px;
  padding: 2px 4px;
}

.toolbar-pdf-link:hover {
  text-decoration: underline;
}

.toolbar-pdf-link:focus-visible {
  outline: 2px solid rgb(var(--v-theme-secondary));
  outline-offset: 2px;
}

.toolbar-divider {
  height: 24px;
  opacity: 0.2;
}

.toolbar-regen {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex: 1;
  min-width: 0;
}

.toolbar-input {
  flex: 1;
  min-width: 140px;
  max-width: 360px;
}

.regen-btn {
  flex-shrink: 0;
  font-weight: 600;
}

.regen-btn:focus-visible {
  outline: 2px solid rgb(var(--v-theme-secondary));
  outline-offset: 2px;
}

/* ── Expanded info ── */
.resume-toolbar__info {
  padding-top: 0.75rem;
  padding-bottom: 0.25rem;
}

.info-text {
  font-size: 0.85rem;
  line-height: 1.65;
  color: rgba(var(--v-theme-on-surface), 0.65);
  margin: 0 0 0.5rem;
}

.info-link {
  color: rgb(var(--v-theme-secondary));
  text-decoration: none;
}

.info-link:hover {
  text-decoration: underline;
}

.info-link:focus-visible {
  outline: 2px solid rgb(var(--v-theme-secondary));
  outline-offset: 2px;
}

/* ── Content ── */
.resume-content {
  flex: 1;
  overflow-y: auto;
}

.resume-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1.25rem;
  padding: 6rem 0;
}

.resume-loading__text {
  font-size: 0.95rem;
  color: rgba(var(--v-theme-on-background), 0.55);
}

.resume-html {
  padding: 1.5rem;
}
</style>