<template>
  <div
    class="menu-bar elevation-2 d-flex flex-column align-start px-4"
    :class="{ 'expanded': isExpanded }"
  >
    <div class="d-flex flex-column flex-lg-row align-center justify-space-between w-100 flex-wrap">
      <!-- Expand Button -->
      <v-btn icon @click="toggleExpand">
        <v-icon>{{ isExpanded ? 'mdi-menu-up' : 'mdi-menu-down' }}</v-icon>
      </v-btn>

      <!-- Official Resume Link -->
      <a
        href="/path-to-your-resume.pdf"
        target="_blank"
        class="d-flex align-center text-decoration-none mb-2 mb-md-0"
      >
        <v-icon class="mr-2">mdi-file-document</v-icon> View Official Resume
      </a>

      <!-- Job Title Input and Regenerate Resume Button Container -->
      <div class="d-flex align-center mb-2 mb-md-0 w-50">
        <!-- Job Title Input -->
        <v-text-field
          v-model="jobTitle"
          label="Looking to hire? Enter the job title!"
          dense
          hide-details
          class="mx-2"
          @keyup.enter="resumeStore.fetchResume(jobTitle)"
        ></v-text-field>

        <!-- Regenerate Resume Button (Now with Label) -->
        <v-btn
          color="primary"
          @click="resumeStore.fetchResume(jobTitle)"
          class="ml-2"
        >
          <v-icon left>mdi-refresh</v-icon>
          Regenerate Resume
        </v-btn>
      </div>
    </div>

    <!-- Expanded Message -->
    <div v-if="isExpanded" class="expanded-message mt-2">
      <p>My resume is being generated by AI.</p>
      <p>I do this to accomplish two things.</p>
      <ol>
        <li>Ensure you get up-to-date relevant information.</li>
        <li>Because I wanted to see if I could.</li>
      </ol>
      <p>My official, hand-made resume is available for download above if you would prefer to look over that.</p>
    </div>
  </div>

  <div>
    <div v-if="resumeStore.loading" class="d-flex flex-column justify-center align-center" style="height: 100vh;">
      <v-progress-circular indeterminate size="64"></v-progress-circular>
      <p class="mt-4 text-center">My resume is being generated. Please wait...</p>
    </div>
    <div v-else v-html="resumeStore.resumeContent"></div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useResumeStore } from '@/stores/resumeStore';

const resumeStore = useResumeStore();
const isExpanded = ref(false);
const jobTitle = ref('');

const toggleExpand = () => {
  isExpanded.value = !isExpanded.value;
};
</script>

<style scoped>
.menu-bar {
  position: sticky;
  top: 0;
  z-index: 10;
  width: 100%;
  background: rgb(var(--v-theme-surface)) !important;
  color: rgb(var(--v-theme-primary)) !important;
  display: flex;
  flex-direction: column;
  transition: height 0.3s ease-in-out;
}

.menu-bar.expanded {
  height: auto;
}

.job-title-label {
  font-size: 0.9rem;
  color: rgb(var(--v-theme-on-surface));
}

.expanded-message {
  opacity: 1;
  transition: opacity 0.3s ease-in-out;
  overflow: auto;
}

.expanded-message ol {
  margin-left: 2rem;
}

@media (max-width: 768px) {
  .menu-bar{
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
